### ISSUE TITLE
Admin panel shows default values but doesn't use them

### ISSUE THREAD

**Issue by UndarkAido** [aunefyren/plex-wrapped#10]
It's probably partially that I'm just dumb, but I assumed that the grayed-out `8181` in the port box meant it would try to connect on that port. I finally figured it out, but you might look into changing how that works.

**Comment by cchiapusio** [comment]
I actually did that at first too.

**Comment by aunefyren** [comment]
Are you referring to the "placeholder", as it's called in HTML? That is a good point, I never thought about it that way. I guess I could find another approach or rename the placeholder to something like "For example: 8181".
