### ISSUE TITLE
Generate non-guessable URLs to distribute to each user

### ISSUE THREAD

**Issue by ponchohoncho** [aunefyren/plex-wrapped#14]
I think some of my users are skeeved out enough by having this kind of watch history, but being able to look up each other's history probably feels worse.

It would be nice to be able to show them their stats without making it possible for anyone to look up anyone else's via email address or username guessing. A unique URL like https://wrapped.myplexserver.com/fc863582-41f7-4877-a11b-90171f357bae would take you to a single user's wrapped, and still allow them to share it if they care to.

**Comment by cchiapusio** [comment]
While this is another feature I'd like (a shareable URL), your core reason is faulty as this is only security through obscurity. The proper solution to enhance privacy is [Plex OAuth](https://github.com/aunefyren/plex-wrapped/issues/9).

**Comment by aunefyren** [comment]
@ponchohoncho I agree with the security aspect, but Plex OAuth is a better approach for that, as @cchiapusio said. The sharing aspect is cool however, so maybe a shareable link could be generated by the user if they want to?

**Comment by ponchohoncho** [comment]
I understand concerns of security through obscurity, but practical considerations need to be taken into account as well. A UUID can have 2^122 possible IDs, and on a server with maybe 30 shared users a good jail or lockout system would very easily take care of ID guessing attacks.

We're also not protecting anything extremely valuable, just a general sense of uneasiness at this kind of tracking, and a sense of privacy that other people can't see what you're watching. There's nothing behind the UUID that is about actual account security, just a few feelings.

If a unique URL is good enough to share Google docs in a "anyone with this link can view" kind of way, I think it's more than good enough for sharing this year-end Plex statistics.

Plex OAuth would work, too, but would be an extra hoop to protect something of middling concern.

**Comment by cchiapusio** [comment]
I would counter that being able to see someone else's watch habits could be very problematic depending on the .... diversity of content hosted on your plex server.

**Comment by ponchohoncho** [comment]
I think that a jail for brute forcers and the incredibly huge address space of a UUID makes guessing URLs a non-issue
