### ISSUE TITLE
times played for movies is wrong

### ISSUE THREAD

**Issue by lasmaty07** [aunefyren/plex-wrapped#15]
On the **List Top Movies** shows a number of movies played, but it's wrong.

for example:
![image](https://user-images.githubusercontent.com/25487723/144637465-b315a118-94e3-4c13-908e-8cdfd68cba37.png)

but this is what tautulli actually shows
Cruella 1 play
![image](https://user-images.githubusercontent.com/25487723/144637051-1e2280f4-b73b-402c-9cf9-ad59ad147ad3.png)
Black Window (none)
![image](https://user-images.githubusercontent.com/25487723/144637670-4f53d3cf-0b16-4071-a05f-2ef53853e96c.png)
Tenet 4 plays.
![image](https://user-images.githubusercontent.com/25487723/144637771-76986950-dac8-46ec-9878-c9418c40112d.png)
 
and so on.

**Comment by aunefyren** [comment]
Mhmm weird. Can you resubmit the images with the grouped watched expanded? It's the '+' sign on the left.

**Comment by lasmaty07** [comment]
Sure,
Cruella Says 10, only 3 on tautulli
![image](https://user-images.githubusercontent.com/25487723/144677752-4c4085bf-4dac-455d-8937-a76548898cef.png)

![image](https://user-images.githubusercontent.com/25487723/144677939-055fb57d-7649-4fcd-a08b-8e848bf39acb.png)

**Comment by aunefyren** [comment]
Thank you.

It is hard to know exactly what is causing this based on this information.

The API combines different history items from Tautulli in different ways. Movie hisotry items watched are combined based on Title and Year comparisons. If two different movies in Tautulli share the same title and year, their duration and plays will be combined in Plex-Wrapped. Tautulli has IDs for media tracking and you can have the same movies history split into different Tautulli entry IDs. It could be that you have multiple Tenet/Cruella entries in your Tautulli database. You can try to check this by going to history and searching for "tenet" or "cruella". Are there more history entries when searching than in the images you sent me?

**Comment by bobokun** [comment]
I also have a similar issue with Cruella showing up as abnormally large time.
![image](https://user-images.githubusercontent.com/12660469/144763479-e0566b5a-d6b9-4b20-a82d-fc35be5a86f3.png)

![image](https://user-images.githubusercontent.com/12660469/144763487-605807ac-a320-4686-bd0e-b8a97c0bf9a9.png)

**Comment by aunefyren** [comment]
Mmm, the plot thickens. @bobokun, if you are comfortable, could you share an image of your Tautulli history search section with a search for 'cruella'? Make sure to search for all user, any library. Only interested in date, title and duration, so feel free to censor anything else.

**Comment by lasmaty07** [comment]
So here it is

![image](https://user-images.githubusercontent.com/25487723/144772366-d41be827-e188-4aa8-bfa5-5a36b4064199.png)

![image](https://user-images.githubusercontent.com/25487723/144772398-eb3677e8-2e73-4dc7-8772-3664fea890ad.png)


I just found the problem. looks like I have 2 movies (or more) on tautulli for each one having issues. but not on my files.

for example cruella:

![image](https://user-images.githubusercontent.com/25487723/144772780-ac827c67-4fc1-46a8-9604-34cd3a6277df.png)

the first one has the ID _7906_ and the other ones _7720_. looks like **radarr** updated the movie (downloaded a better version) and tautulli creates a new id for that movie. So when seaching in tautulli in the Libraries section, only shows the new version. which has only been seen by 1 person [this image](https://user-images.githubusercontent.com/25487723/144637051-1e2280f4-b73b-402c-9cf9-ad59ad147ad3.png)

Thanks.

**Comment by aunefyren** [comment]
That is what I hoped was causing this issue, haha. Thank you for checking @lasmaty07! :)

If you go to the duplicated media entries in Tautulli you can press Fix Match to merge items, if you wish.

**Comment by lasmaty07** [comment]
> If you go to the duplicated media entries in Tautulli you can press Fix Match to merge items, if you wish.

that's the thing, I don't have them duplicated.

thanks anyway
