### ISSUE TITLE
Server-wide statistics shows NaN total seconds of playback

### ISSUE THREAD

**Issue by hunsbct** [aunefyren/plex-wrapped#16]
The container with total server-wide playback shows the following text:

```
All the different users combined spent
40 days, 12 hours and 28 minutes
watching movies.

All the different users combined spent
80 days, 23 hours and 39 minutes
watching shows.

That is
NaN seconds
of content!
```

**Comment by aunefyren** [comment]
Have you updated since this commit, 104b4c9? It was supposed to fix this bug.

**Comment by hunsbct** [comment]
I should have included this in the original item, but it is occurring in a docker instance that I just pulled about an hour ago via the Unraid app listing:

![image](https://user-images.githubusercontent.com/15640258/144752245-1bdb2aa8-79f5-4b05-a8a3-3fad911fc4d1.png)

Since you've already fixed the bug, I assume it would be up to the owner of that repository to get the image up to date.

**Comment by aunefyren** [comment]
Yes, I am not familiar with Unraid, but the Docker fetches the latest verison from GitHub, so the Unraid app is probably in a fixed state.

**Comment by ctrlaltd1337ed** [comment]
> Yes, I am not familiar with Unraid, but the Docker fetches the latest verison from GitHub, so the Unraid app is probably in a fixed state.

Docker Hub latest update was 9 days ago, and it looks like the fix was published after that. Can you push the latest changes to docker Hub so that the unRAID app template will have the fix as well?

**Comment by aunefyren** [comment]
Alright, @ctrlaltd1337ed. Added a GitHub release and changed the Docker image to represent releases.

**Comment by ctrlaltd1337ed** [comment]
> Alright, @ctrlaltd1337ed. Added a GitHub release and changed the Docker image to represent releases.

Thanks! At the risk of sounding needy, are you able to change the tag on DockerHub to `latest`? The template is set up to pull from that tag, so it is currently broken. If any further changes come up, you can leave `v2.0.0` as a version, and all new releases can go under `latest`.

**Comment by aunefyren** [comment]
@ctrlaltd1337ed, I didn't want to use 'latest' as I felt the Docker image should reflect the release you are getting, but I noticed you can add multiple tags, so the release now has 'v2.0.0' and 'latest'. This could provide the best of both worlds, so hope it works.

**Comment by cchiapusio** [comment]
@aunefyren That is the correct solution, thank you.

**Comment by ctrlaltd1337ed** [comment]
That looks to have worked, thank you. 

Just a note, I was still getting NaN seconds in my Wrapped results, until I disabled `Get users music statistics` but enabled `Get server-wide music statistics`.
